=== robertgluszkiewicz/task-set/src/main/resources/bank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bank">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="employee_id" type="xs:integer"/>
                                        <xs:element name="first_name" type="xs:string"/>
                                        <xs:element name="last_name" type="xs:string"/>
                                        <xs:element name="birth_date" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="departments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="department" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="accounts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="account" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="account_id" type="xs:integer"/>
                                        <xs:element name="account_number" type="xs:string"/>
                                        <xs:element name="balance" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="cards">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="card" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="card_id" type="xs:integer"/>
                                        <xs:element name="card_number" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="branches">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="branch" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="country" type="xs:string"/>
                                        <xs:element name="city" type="xs:string"/>
                                        <xs:element name="employees_number" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== robertgluszkiewicz/task-set/src/main/resources/bank.xml
<?xml version="1.0" encoding="UTF-8"?>

<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bank.xsd">
    <employees>
        <employee>
            <employee_id>1</employee_id>
            <first_name>John</first_name>
            <last_name>Smith</last_name>
            <birth_date>2000-01-30</birth_date>
        </employee>
        <employee>
            <employee_id>2</employee_id>
            <first_name>Lara</first_name>
            <last_name>Brown</last_name>
            <birth_date>1999-08-17</birth_date>
        </employee>
    </employees>
    <departments>
        <department>
            <name>Sales</name>
        </department>
        <department>
            <name>Marketing</name>
        </department>
        <department>
            <name>Human Resources</name>
        </department>
    </departments>
    <accounts>
        <account>
            <account_id>11</account_id>
            <account_number>123456789</account_number>
            <balance>350.18</balance>
        </account>
        <account>
            <account_id>22</account_id>
            <account_number>1111000022</account_number>
            <balance>5000.55</balance>
        </account>
    </accounts>
    <cards>
        <card>
            <card_id>111</card_id>
            <card_number>90897060</card_number>
        </card>
        <card>
            <card_id>333</card_id>
            <card_number>90222903</card_number>
        </card>
    </cards>
    <branches>
        <branch>
            <country>Italy</country>
            <city>Rome</city>
            <employees_number>24</employees_number>
        </branch>
        <branch>
            <country>Spain</country>
            <city>Madrid</city>
            <employees_number>53</employees_number>
        </branch>
        <branch>
            <country>England</country>
            <city>London</city>
            <employees_number>16</employees_number>
        </branch>
    </branches>
</bank>
